server:
  port: 8083

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: bookstore_user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# ✅ OUTSIDE spring
resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      productService:
        maxAttempts: 3          # 1 original + 2 retries
        waitDuration: 1s        # delay between retries
        retryExceptions:
          - java.lang.Exception
feign:
  client:
    config:
      default:
        connectTimeout: 3000   # 3 sec
        readTimeout: 3000      # 3 sec


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/