server:
  port: 8083

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: bookstore_user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      productService:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - java.lang.Exception

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false